export const LOGIN_LOADING="LOGIN_LOADING";
export const LOGIN_ERR="LOGIN_ERR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";


export const USER_REGISTRATION_LOADING="USER_REGISTRATION_LOADING";
export const USER_REGISTRATION_ERR="USER_REGISTRATION_ERR";
export const USER_REGISTRATION_SUCCESS="USER_REGISTRATION_SUCCESS";

export const USER_PROFILE_LOADING="USER_PROFILE_LOADING"
export const USER_PROFILE_ERR="USER_PROFILE_ERR";
export const USER_PROFILE_SUCCESS="USER_PROFILE_SUCCESS";

